name: deploy to prod 8600
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        command_timeout: 200m
        script: |
          git config --global --add safe.directory /apps/github-workflows/kenyaemr-modules/openmrs-module-covid19      
          cd /apps/github-workflows/kenyaemr-modules/openmrs-module-covid19
          git pull origin master
          git status
          mvn clean install -DskipTests
          sudo rm -rf /var/lib/OpenMRS/modules/covid19-*.omod
          sudo cp /apps/github-workflows/kenyaemr-modules/openmrs-module-covid19/omod/target/covid19-*.omod /var/lib/OpenMRS/modules/
          sudo chown -R tomcat:tomcat /var/lib/OpenMRS/modules/
          sudo chmod +r /var/lib/OpenMRS/modules/*.omod
          sudo chmod 755 /var/lib/OpenMRS/modules/*.omod
          sudo service tomcat9 restart
         
